### ISSUE TITLE
Integration Spec failing

### ISSUE THREAD

**Issue by marshallshen** [brainopia/symbolic#8]
I forked the project and I run the spec tests, and there are bunch of integration_spec tests fail:
Failures:

  1) Symbolic to_s: -x-y
     Failure/Error: expr.to_s.should == str
       expected: "-x-y"
            got: "-y-x" (using ==)
     # ./spec/integration_spec.rb:162

  2) Symbolic to_s: 2/(x_y)
     Failure/Error: expr.to_s.should == str
       expected: "2/(x_y)"
            got: "2/(y*x)" (using ==)
     # ./spec/integration_spec.rb:162

  3) Symbolic to_s: -x_y
     Failure/Error: expr.to_s.should == str
       expected: "-x_y"
            got: "-y*x" (using ==)
     # ./spec/integration_spec.rb:162

  4) Symbolic to_s: 4_(y+3)_(x+2)
     Failure/Error: expr.to_s.should == str
       expected: "4_(y+3)_(x+2)"
            got: "4_(x+2)_(y+3)" (using ==)
     # ./spec/integration_spec.rb:162

  5) Symbolic to_s: -x+y
     Failure/Error: expr.to_s.should == str
       expected: "-x+y"
            got: "y-x" (using ==)
     # ./spec/integration_spec.rb:162

  6) Symbolic to_s: x_y
     Failure/Error: expr.to_s.should == str
       expected: "x_y"
            got: "y*x" (using ==)
     # ./spec/integration_spec.rb:162

I will dig into the code and try to submit a patch to fix the issue.

**Comment by marshallshen** [comment]
It turns out that it's more of a ruby version issue. I updated my ruby from version 1.8.7 to 1.9.2 and the tests are all passed.
Sorry for the confusion.

**Comment by eregon** [comment]
Indeed, it is related to the ruby version and the Hash ordering.
symbolic is 1.9 only atm and we are probably going to require ruby 1.9, although there was an attempt to make it 1.8 compatible.
Please tell us if you would be interested in a 1.8-compatible symbolic.
